### PR TITLE
inference patterns for feature lookup

### PR DESCRIPTION
**Pull request by RominaUQ**
Added 2 sample notebooks for inference patterns
Custom library folder containing helper functions and scripts
2 images

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by markproy — COMMENTED** [review]
bug: inference script has hard-coded feature group names. should use SM endpoint environment variables instead.

typo: 'Load the traind model to use for inference'. wording: "if you would like to play around a bit"

since the nb creates the inference script, should not include it in the repo as a separate file in the custom_library folder.

**Comment by markproy** [comment]
lookup of features from two feature groups is taking 700+ ms, and in one case took 4.9 SECONDS. this is unacceptable perf. we'll need to troubleshoot w/ service team and with Anoop Sanka before shipping this.

**Comment by RominaUQ** [comment]
Using the new helper library that uses the caching, I still was seeing range between 0.2 to 0.4 for features loop up from feature store  ( among few runs I tried...).

**Comment by pmhargis-aws** [comment]
Tested latest notebook and inference code from PR #11 branch 'new_branch' 

ERROR found at bottom of `m4_nb2_Inference_endpoint_lookup.ipynb`

Code:
`feature_list=['fscw-products-10-18-00-12:*','fscw-customers-10-18-00-12:*']
`
this hard-coded reference to feature_group name will not work, and results in this error:

---> 31         _desc = sagemaker_client.describe_feature_group(FeatureGroupName=fg_name)
ResourceNotFound: An error occurred (ResourceNotFound) when calling the DescribeFeatureGroup operation: Resource Not Found: Amazon SageMaker can't find a FeatureGroup with name fscw-products-10-18-00-12

**Comment by pmhargis-aws** [comment]
Debugging ERROR above, for "Optional" section at bottom, running local test of `input_fn`, I had to do 2 things:
1) use the original values for `feature_list` that are read from parameter store

2) add this line to `helper.py` function (like you did in `inference.py`):

` features=ast.literal_eval(features)`

**Pull request merged**
