### PR TITLE
Batch transform example

### PR DESCRIPTION
**Pull request by acere**
*Description of changes:*
- Added a new notebook, `m3_nb2_batch_transform.ipynb`, to module 3 of the workshop to demonstrate how to create a dataset from offline feature store and score it using SageMaker Batch Transform.
- added `.gitignore` file to reduce chances of accidental commit of temporary and system files

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by markproy — COMMENTED** [review]
batch_transform.ipynb says "This notebook uses the feature set extracted by module-2 to create a XGBoost based machine learning model for binary classification" in markdown at top. needs to be corrected.

**Comment by markproy** [comment]
also batch_transform.ipynb, one suggestion, not critical, but I'd see the "rank=1" clauses more intuitively placed with the "table as" clauses instead of in the final where clause for the query.

**Comment by markproy** [comment]
prior 2 comments also apply to the "_parquet.ipynb" notebook.

**Comment by markproy** [comment]
need to consider restructuring the modules, as this is adding "batch transform" into a module called "feature transformation and training". likewise, depending on how we land with modules, need to update the module README in addition to the module naming. plus the overall workshop README to highlight the additional capability to do batch.

**Comment by markproy** [comment]
last comment... it is not clear enough why we have 2 examples of doing batch scoring, one for parquet. need to motivate that a bit further. likewise, need to add some markdown to explain that the query could have also been done just using PyAthena or boto3 athena, but that .... [insert explanation here] ...

**Comment by melanie531** [comment]
> also batch_transform.ipynb, one suggestion, not critical, but I'd see the "rank=1" clauses more intuitively placed with the "table as" clauses instead of in the final where clause for the query.

The "rank" column is only available after the CTE, therefore we need to put it at the final where clause

**Comment by markproy** [comment]
> last comment... it is not clear enough why we have 2 examples of doing batch scoring, one for parquet. need to motivate that a bit further. likewise, need to add some markdown to explain that the query could have also been done just using PyAthena or boto3 athena, but that .... [insert explanation here] ...

I don't see this being addressed.

**Comment by jonreadeMLdemos** [comment]
Attempted the update for the sub folder, both with the absolute path given and the relative path. First failed, second didn't, however no new files appeared in the sub-folder. Refreshed the folder after a few minutes, but still no sign of the files. Please see attached screenshot.
Module 8 Batch Transform Run 2021-11-24 1926 UTC

**Comment by acere** [comment]
@jonreadeMLdemos is this specific to this PR?
BTW, did you try to clone with `--recursive` option? I've created a separate issue to update the README #14

**Comment by pmhargis-aws** [comment]
Testing of content was successful! 

The two notebooks on Batch Scoring are highly similar, and need to have different titles (markdown), introductory paragraphs, etc. One appears to use an inline (local) Athena query to create dataset for batch transform, while the other one runs an SKLearnProcessor job to effectively do the same thing -- I assume this is the primary difference. 

Can we modify introductory paragraph to indicate this?

**Comment by pmhargis-aws** [comment]
I will go ahead and merge PR, and open issue to track updates to notebook titles, etc.

**Pull request merged**
