### PR TITLE
Module security

### PR DESCRIPTION
**Pull request by lauerarnaud**
*Issue #, if available:*

*Description of changes:*
A couple of changes included in the PR
1) Update to the granular permission setup notebook with instructions to add additional permissions to the execution role to prevent direct access to S3
2) New notebook for implementing feature group level access control (online/offline) using IAM policy (tag based approach)
3) reorganised 09-security-module with subfolder for the two above approaches

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pmhargis-aws** [comment]
Per notebook: 09-module-security/09-01-granular-access-control-lake-formation-offline/m9_01_nb0_row_cell_level_access_lf_setup.ipynb

Please add print statements for feature group names to ensure they are properly loaded from storage:

print(customers_feature_group_name)
print(orders_feature_group_name)
print(products_feature_group_name)

**Comment by pmhargis-aws** [comment]
ERROR:  pyathena module was not installed

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-06aa161ee564> in <module>
      6 import boto3
      7 import sys
----> 8 from pyathena import connect
      9 import pandas as pd
     10 sys.path.append('..')

ModuleNotFoundError: No module named 'pyathena'

**Comment by pmhargis-aws** [comment]
Per notebook: 09-module-security/09-01-granular-access-control-lake-formation-offline/m9_01_nb0_row_cell_level_access_lf_setup.ipynb

ERROR: 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-31e5c7fb0427> in <module>
      9 import pandas as pd
     10 sys.path.append('..')
---> 11 from utilities import Utils
     12 from utilities import feature_store_helper
     13 

ModuleNotFoundError: No module named 'utilities'

**Comment by lauerarnaud** [comment]
Thanks @pmhargis-aws I have committed a new version of the notebook to address all the comments.  Thanks.

**Comment by pmhargis-aws** [comment]
Merged the Pull-Request from module-security branch.

**Pull request merged**
